### ISSUE TITLE
Add more filtering options for account transactions

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-wallet-proxy#13]
**Task description**

We need the wallet proxy accTransactions endpoint to support:
• Get only encrypted transfers (this means all of shield, unshield, encrypted transfer transaction types)
• Specify block time from/to, and only get transactions in the given timespan.
• Filter by reward type (add an option to show only baker rewards, it would fulfil the needs and not break the existing implementation)
   ◦ Block rewards (already exists).
   ◦ Baker rewards .
   ◦ Finalization rewards (already exists).

If clarification is needed talk to the desktop wallet team.

**Comment by abizjak** [comment]
@soerenbf for your reference and tracking.

**Comment by SimonKamp** [comment]
Should block time from/to be in seconds from epoch? And can I assume they are integers, or should we accept Doubles since that is what we use for the response?

**Comment by soerenbf** [comment]
> Should block time from/to be in seconds from epoch? And can I assume they are integers, or should we accept Doubles since that is what we use for the response?

I think seconds from epoch (integers) would be fine. Pretty sure this is what we're working with in other places as well.

**Comment by abizjak** [comment]
> > Should block time from/to be in seconds from epoch? And can I assume they are integers, or should we accept Doubles since that is what we use for the response?
> 
> I think seconds from epoch (integers) would be fine from the perspective of the desktop wallet. Pretty sure this is what we're working with for transactions in other places as well?

Block times are in general not integral numbers of seconds since the epoch since slot duration is in ms. Transaction expiry times are in seconds though.

I think for the query input it makes sense they are integral numbers of seconds.

**Comment by soerenbf** [comment]
> Transaction expiry times are in seconds though.

This was the one I had in mind 😄
