### ISSUE TITLE
Problem with Id Provider list on Testnet.

### ISSUE THREAD

**Issue by smh1001** [Concordium/concordium-wallet-proxy#17]
**Bug Description**
On testnet the wallet proxy returns 3 identity providers (see screenshot). The two notabene providers have the same name and only one of them work. 
![image](https://user-images.githubusercontent.com/76111660/127446479-97ebf724-42fb-4e30-9b94-c6eb57369644.png)

We should probably remove the "fake" Notabene one since it does not work.

**Steps to Reproduce**
Create an identity on testnet.

**Expected Result**
All id providers listed should work.
It should be possible to distinguish id providers by the name listed.

**Actual Result**
The two Notabene providers cannot be distinguished and only one of the works.

**Versions**
Desktop wallet 1.1.6 on windows 10.

**Comment by abizjak** [comment]
This is not an issue with the wallet-proxy, but rather with the deployment. The configuration file that the proxy is deployed with needs to be updated and the proxy redeployed.

**Comment by abizjak** [comment]
The wallet-proxy on testnet has been redeployed with the updated configuration file, so closing this.

**Comment by smh1001** [comment]
@abizjak Thanks for updating the config. Where should config related issues be reported?

**Comment by abizjak** [comment]
@smh1001 I think the internal devops board is the best place for this since they are ultimately responsible for managing the configuration and services.
