### ISSUE TITLE
Running a query against local node

### ISSUE THREAD

**Issue by sderuiter** [Concordium/concordium-wallet-proxy#40]
**Bug Description**
`curl -XGET https://localhost:10000/v0/accBalance/4WHFD3crVQekY5KTJ653LHhNLmTpbby1A7WWbN32W4FhYNeNu8` should run a query against my local node.
It returns:
`curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`

**Steps to Reproduce**
Enter above command

**Expected Result**
Same result as if you were queuing the online wallet-proxy url.
**Actual Result**
See above.

macOS Monterey 12.1.

**Comment by abizjak** [comment]
The node's API is gRPC. The wallet-proxy exposes an alternate http rest-like API designed for the mobile wallet.

So you cannot query the node like this. You need to make a gRPC call, and use the correct endpoint (e.g., for getting the account balance the relevant method is GetAccountInfo).

**Comment by sderuiter** [comment]
Can you give an example? I'm currently using Concordium-client calls, but would much rather have the json output from the wallet-proxy.

**Comment by abizjak** [comment]
You can get JSON output with `raw` commands.

So 
```
concordium-client raw GetAccountInfo 4WHFD3crVQekY5KTJ653LHhNLmTpbby1A7WWbN32W4FhYNeNu8
```

But the API is not the same as for the proxy. The proxy does a bit of transformation to make it easier for the wallet to consume.

**Comment by sderuiter** [comment]
That is actually very useful, and will get rid of 300+ LOC of ugly string hacking. Thanks!
