### ISSUE TITLE
Forward request and response cookies.

### ISSUE THREAD

**Issue by vikt0r0** [Concordium/concordium-wallet-proxy#65]
Forward cookie headers in requests and set-cookie headers in responses to wallet proxy. This ensures that the user of the proxy receives data from the same node with subsequent requests (since the load-balancer between the wallet proxy and nodes map cookie values to a specific nodes). Specifically,

Client:
- [x] Modify concordium-client, s.t. we can set request cookies in requests to node.
- [x] TLS should be supported for node queries.

Wallet-proxy:
- [x] Forward request cookies.
- [x] Forward set-cookie headers in response to user.
- [x] Implement set-cookie in wallet-proxy s.t. subsequent requests in wallet proxy include such cookies; in this case the wallet proxy acts as a client.
- [x] The wallet-proxy should log all the headers related to cookies it is translating.
- [x] Test that set-cookies are received by user and that wallet-proxy forwards cookies sent from user.
- [x] Add log levels and log-level command-line parameter.

**Comment by abizjak** [comment]
As discussed, the task needs to be revised a bit
- all Cookie's need to be sent from the client to the node by the proxy
- all Set-Cookie and Cookie headers should be forwarded from the node back to the client
- TLS should be supported for node queries.

**Comment by vikt0r0** [comment]
I checked off logging. It currently logs at info level, not sure how to do it at trace level, however. Should this be looked into?

**Comment by abizjak** [comment]
We can use `logOther "Trace"` and then configure the logger at runtime with whether it should or should not support logging.
